---
title: "R Notebook"
output: html_notebook
---

```{r eval=false}
#Library####
library("annotate")
library("heatmap3")
library("Biobase")
library("tools")
library("AnnotationDbi")
library("annotate")
library("heatmap3")
library(RColorBrewer)
library("ade4")
library("ALL")
library("gplots")
library(ggplot2)
library("ALL")
library("ade4")
#library("mixOmics")
library("RVAideMemoire")
library(limma)
library("affy")
library("pd.huex.1.0.st.v2")
#library("hugene10sttranscriptcluster")
#library("huex10sttranscriptcluster.db")
library('gcrma')
library(oligo)
#library(hugene10stv1cdf)
library(dplyr)
library("hgu133plus2.db")


```


```{r eval=false}
library(readxl)
library(GEOquery)
#Data import#####
wd_a <- "/Users/olivier/Desktop/Projet/Test/"
knitr::opts_chunk$set(root.dir = wd_a)
#setwd(wd_a)
# Accessing Raw Data from GEO:
my_id = "GSE145408"
filePaths = getGEOSuppFiles(my_id)
```



```{r eval=false}
### Import data ----

#Lecture du fichier Target
file_pheno_xlsx <-paste0(my_id,"_Target.xlsx")
file_pheno <- paste0(my_id,"_Target.txt")

data <- read_excel(paste0(wd_a,my_id,"/",file_pheno_xlsx))

write.table(data, file = file_pheno, sep = "\t", row.names = TRUE)
pheno <- read.table(file = file_pheno, header = TRUE, sep = "\t", row.names = 1)

pd <-read.AnnotatedDataFrame(file = file_pheno,row.names = 1, header=TRUE,as.is=TRUE, sep = "\t")

pd <- read.AnnotatedDataFrame(file = file_pheno, row.names = 1, header = TRUE, as.is = TRUE, sep = "\t", col.names = c("GSM", "Group", "Patient", "Time", "Group_short","Description", "File"))

# Iterate through each column of pd
for (col in colnames(pd)) {
  # Remove double quotes from the column
  pd[[col]] <- gsub("\"", "", pd[[col]])
}

```

```{r}
#Changement de wd (besoin d'extraire le fichier RAW)
wd <- paste0(wd_a,my_id,"/",my_id,"_RAW")
df1 <- getGSEDataTables #??


knitr::opts_chunk$set(root.dir = wd)
write.table(matrix(dir()),file="a-list-files.txt", sep="\t")
```


```{r}
#Reads CEL files
library(oligo)


rawAffyData <- read.celfiles(filenames = pData(pd)$File, phenoData = pd)


exprs(rawAffyData)[1:4,1:3]
#boxplot(rawAffyData, which=c("all"))
#hist(rawAffyData)
#hist(rawAffyData, which=c("all"))
#pmSeq <- pmSequence(rawAffyData)
#pmSeq[1:5]

colnames(rawAffyData)

# Normalizes data ####
#Summarised per gene:
eset <- oligo::rma(rawAffyData)
#boxplot(eset)
#change directory: ####
# annotate: #### Selon la puce, changer le package d'annotation

library(affycoretools)

#library(hugene20sttranscriptcluster.db)
#BiocManager::install("hgu133plus2.db")
library(hgu133plus2.db)
eset <-annotateEset(eset,hgu133plus2.db)
#eset <- annotateEset(eset, hugene20sttranscriptcluster.db )
#eset <- annotateEset(eset, pd.hugene.2.1.st)

geneName = "GAPDH"
which(fData(eset)$SYMBOL == geneName )
```


```{r}
#head(fData(eset))

# filtration:
eset_medians <- rowMedians(Biobase::exprs(eset))
hist_res <- hist(eset_medians, 100, col = "cornsilk1", freq = FALSE, 
                 main = "Histogram of the median intensities", 
                 border = "antiquewhite4",
                 xlab = "Median intensities")
median(eset_medians)

man_threshold =median(eset_medians)
abline(v = median(eset_medians), col = "grey", lwd = 2)
abline(v = man_threshold, col = "coral4", lwd = 2)

length(which((rowMedians(exprs(eset)) >= man_threshold) == "TRUE"))
data_filtr  <- eset[rowMedians(exprs(eset)) >= man_threshold,]
dim(data_filtr)
dim(eset)

toto <- cbind(fData(data_filtr), exprs(data_filtr))
dim(toto)
write.table(toto, file="c-affy-Norm-Glomeruli-8April21.txt", sep="\t")


##enlever gene sans Symbol: ####
length(which(is.na(fData(data_filtr)$SYMBOL) ==T ))
index <- which(is.na(fData(data_filtr)$SYMBOL) ==T )
sansNA <- data_filtr[-index, ]
length(which(is.na(fData(sansNA)$SYMBOL) ==T ))
dim(sansNA)
dim(eset)
dim(data_filtr)

sansNA_medians <- rowMedians(Biobase::exprs(sansNA))
hist_res <- hist(sansNA_medians, 100, col = "cornsilk1", freq = FALSE, 
                 main = "Histogram of the median intensities", 
                 border = "antiquewhite4",
                 xlab = "Median intensities")
##### END import #####

```

